pipeline{
    agent any
    stages{
        stage('Checkout Code'){
            steps{
                git ''
            }
        }
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('Package'){
            steps{
                sh 'mvn package'
            }
        }
        stage('Notify'){
            steps{
                echo 'Build and Package completed successfully!'
            }

        }
    }
}